### ISSUE TITLE
multi rar file extract doesn't work

### ISSUE THREAD

**Issue by hojjung** [siblount/DazProductInstaller#29]
i dragged 200files of rar
and the task just complete 1 file
and removed all of my daily whole downloaded contents

**Comment by hojjung** [comment]
i think the matter is if one file installing done
every task just done forcely

**Comment by hojjung** [comment]
I feel like I’d be really grateful if you could just solve this one problem. It seems like it just needs a good adjustment to the task termination conditions. My understanding of this project is too limited to effectively debug while testing. But if you take a look, I think you could fix it quickly. In some cases, all files get installed, but in others, they don’t. It seems like the whole process ends if just one file finishes

**Comment by siblount** [comment]
Woah! 

Which version did you use? Was it the latest (which is [v0.9 Pre-Release](https://github.com/siblount/PMForDAZ/releases/tag/v0.9.8779.23016-Pre-Alpha))?

Also, although time has probably passed by since it has happened, you should've had a log file that would immediately explain everything to me. Perhaps, if you are willing, could you reproduce by running the same RAR file again and providing me with the logs? It _should_ be in the same directory where you installed the installer.

By 'removed all of my daily whole downloaded contents', are you referring to the '200 files of rar'? Or in other words, it removed all the files you dragged to the program?

I do recall an issue with the archives not extracting properly but I believe I fixed it. But the deletion of source archive files should only occur if the "Remove Source File(s)" is set to Yes or if set to "Prompt" it will ask you if you want to remove them.

**Comment by hojjung** [comment]
1. The removed files were all deleted using that option; I am aware of this.
2. The main issue is that the files didn’t install but still went through the removal phase.
3. The bug seems to occur when the program moves to the removal phase right after completing the task for a single file, without waiting for all tasks to finish.

I used to download DAZ files from 3dcu.com. You can test it with some RAR files from there.
Also, the database confirmed that the same product key was registered multiple times. This was a bit annoying, and I think you should manage the database to prevent duplicate entries.
For example, when I removed one of the duplicate entries, the other product with the same key also broke.
Of course, they both pointed to the same file path.

so you should overwrite or block when same product adding to database
or make a merge & distinct  button

**Comment by siblount** [comment]
I'll take a look into those issues, but first can you tell me which version you used?

Also, do you have a RAR file that consistently fails? That would be good for my tests too.

The merging logic will be a bit more involved - I'll ponder on this idea and I'll get back to you.

**Comment by siblount** [comment]
Going back to the main issue the title describes, "multi rar file extract doesn't work", and "the task just complete 1 file
and removed all of my daily whole downloaded contents", it seems that I am able to reproduce for the latest _pending_ version (in `pending-main` branch).

The program raised an expected error that the "The archive is not the first volume out of a multi-volume archive. Only input the first volume". The problem was most likely caused by @hojjung providing a rar file that was not the first part of the archive.

The latest pending version seems to not prompt to remove source files if the extraction was a failure. But, there still needs to be validation and more UI indicators to prevent this from happening.

Error log:
```
[2024-12-20 14:56:20 INF] [Thread 7] [DPProcessor]: Entering archive Test_split_solid.part2.rar
[2024-12-20 14:56:20 INF] [Thread 7] [DPProcessor] [Test_split_solid.part2.rar]: Processing archive
[2024-12-20 14:56:20 DBG] [Thread 7] [DPProcessor]: Archive that is about to be processed: {"Name":"Test_split_solid.part2.rar","NestedArchive":false,"Path":"C:\\Users\\User\\Desktop\\Test_split_solid.part2.rar","Extractor":"DPRARExtractor","ParentArchiveNestedArchive":null,"ParentArchiveName":null,"ParentArchivePath":null,"ParentExtractor":null}
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: Preparing to peek
[2024-12-20 14:56:20 WRN] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: The current destination directory is not whitelisted and will not be created
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume.
[2024-12-20 14:56:20 INF] [Thread 7] [DPProcessor]: Preparing operations
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor]: Extracting to temp
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: Preparing to extract
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: Preparing to peek
[2024-12-20 14:56:20 WRN] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: The current destination directory is not whitelisted and will not be created
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume.
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: Preparing to extract
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: Preparing to peek
[2024-12-20 14:56:20 WRN] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: The current destination directory is not whitelisted and will not be created
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume.
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume
[2024-12-20 14:56:20 INF] [Thread 7] [DPProcessor]: Analyzing the archive - fetching tags
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor]: Extracting to temp
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: Preparing to extract
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: Preparing to peek
[2024-12-20 14:56:20 WRN] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: The current destination directory is not whitelisted and will not be created
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume.
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split_solid.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume
[2024-12-20 14:56:20 WRN] [Thread 7] [DPProcessor]: Exiting archive Test_split_solid.part2.rar with failures
[2024-12-20 14:56:20 DBG] [Thread 7] [DPProcessor]: Archive exit report: {"SuccessPercentage":0,"$type":"DPExtractionReport"}
[2024-12-20 14:56:20 INF] [Thread 7] [DPProcessor]: Entering archive Test_split.part2.rar
[2024-12-20 14:56:20 INF] [Thread 7] [DPProcessor] [Test_split.part2.rar]: Processing archive
[2024-12-20 14:56:20 DBG] [Thread 7] [DPProcessor]: Archive that is about to be processed: {"Name":"Test_split.part2.rar","NestedArchive":false,"Path":"C:\\Users\\User\\Desktop\\Test_split.part2.rar","Extractor":"DPRARExtractor","ParentArchiveNestedArchive":null,"ParentArchiveName":null,"ParentArchivePath":null,"ParentExtractor":null}
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: Preparing to peek
[2024-12-20 14:56:20 WRN] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: The current destination directory is not whitelisted and will not be created
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume.
[2024-12-20 14:56:20 INF] [Thread 7] [DPProcessor]: Preparing operations
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor]: Extracting to temp
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: Preparing to extract
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: Preparing to peek
[2024-12-20 14:56:20 WRN] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: The current destination directory is not whitelisted and will not be created
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume.
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: Preparing to extract
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: Preparing to peek
[2024-12-20 14:56:20 WRN] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: The current destination directory is not whitelisted and will not be created
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume.
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume
[2024-12-20 14:56:20 INF] [Thread 7] [DPProcessor]: Analyzing the archive - fetching tags
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor]: Extracting to temp
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: Preparing to extract
[2024-12-20 14:56:20 INF] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: Preparing to peek
[2024-12-20 14:56:20 WRN] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: The current destination directory is not whitelisted and will not be created
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume.
[2024-12-20 14:56:20 ERR] [Thread 7] [DPRARExtractor] [Test_split.part2.rar]: The archive is not the first volume out of a multi-volume archive. Only input the first volume
[2024-12-20 14:56:20 WRN] [Thread 7] [DPProcessor]: Exiting archive Test_split.part2.rar with failures
[2024-12-20 14:56:20 DBG] [Thread 7] [DPProcessor]: Archive exit report: {"SuccessPercentage":0,"$type":"DPExtractionReport"}
[2024-12-20 14:56:20 ERR] [Thread 1] [DPExtractJob]: An error occurred while attempting to add archive to list
System.NullReferenceException: Object reference not set to an instance of an object.
   at DAZ_Installer.Windows.Pages.Extract.AddToHierachy(IDPArchive workingArchive) in D:\a\PMForDAZ\PMForDAZ\src\DAZ_Installer.Windows\Pages\Extract.cs:line 86
   at DAZ_Installer.Windows.DP.DPExtractJob.<Processor_StateChanged>b__29_0() in D:\a\PMForDAZ\PMForDAZ\src\DAZ_Installer.Windows\DP\DPExtractJob.cs:line 83
   ```

**Comment by siblount** [comment]
@hojjung I suspect that the issue is caused when you dragged all parts of a multi-part RAR file. For example, given you have the following:
```
test.part1.rar
test.part2.rar
```
You should only provide `test.part1.rar`; the program will search for `test.part2.rar` in the same directory where `test.part1.rar` is located. This is also true for multi-part 7z files, only provide the file with the extension `.001`.

Can you confirm when you provided the program with 200 RAR files that you also provided multiple parts of the RAR file?

**Comment by hojjung** [comment]
> @hojjung I suspect that the issue is caused when you dragged all parts of a multi-part RAR file. For example, given you have the following:
> 
> ```
> test.part1.rar
> test.part2.rar
> ```
> 
> You should only provide `test.part1.rar`; the program will search for `test.part2.rar` in the same directory where `test.part1.rar` is located. This is also true for multi-part 7z files, only provide the file with the extension `.001`.
> 
> Can you confirm when you provided the program with 200 RAR files that you also provided multiple parts of the RAR file?

oh yes i think it was
